# Generated by Django 4.0.5 on 2022-07-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('birth_day', models.DateTimeField()),
                ('photo', models.ImageField(default=None, upload_to='uploads/%Y/%m')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('last_name', 'first_name')},
            },
        ),
    ]
