# Generated by Django 4.0.5 on 2022-07-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, upload_to='uploads/%Y/%m'),
        ),
    ]
