# Generated by Django 4.0.5 on 2022-08-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, upload_to='project/static/uploads/%Y/%m'),
        ),
    ]
