# Generated by Django 4.0.5 on 2022-07-15 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='complete_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
