# Generated by Django 4.0.5 on 2022-07-15 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_boxchat_alter_position_unique_together_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('isExtra', models.BooleanField(default=True)),
                ('desc', models.TextField(null=True)),
                ('process_name', models.CharField(max_length=200)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='boxchat',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_boxchat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('work_name', models.CharField(max_length=200)),
                ('desc', models.TextField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('isProcess', models.BooleanField(default=False)),
                ('cost', models.FloatField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('complete_date', models.DateTimeField(null=True)),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.process')),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='user_work', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('step_name', models.CharField(max_length=200)),
                ('desc', models.TextField(null=True)),
                ('isAccept', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.process')),
                ('user_accept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('users_notification', models.ManyToManyField(blank=True, null=True, related_name='user_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
