# Generated by Django 4.0.5 on 2022-07-20 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_user_device_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('document_name', models.CharField(max_length=200)),
                ('isWork', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.process')),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.work')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
