# Generated by Django 4.0.5 on 2022-07-20 02:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalwork',
            name='users_notification',
            field=models.ManyToManyField(blank=True, related_name='user_noti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boxchat',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user_boxchat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='step',
            name='users_notification',
            field=models.ManyToManyField(blank=True, related_name='user_notification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='work',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user_work', to=settings.AUTH_USER_MODEL),
        ),
    ]
