# Generated by Django 4.0.5 on 2022-07-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_alter_additionalwork_users_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=None, upload_to='documents/%Y/%m'),
        ),
    ]
