# Generated by Django 4.0.5 on 2022-07-20 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='project.stage'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='project.project'),
        ),
    ]
