# Generated by Django 4.0.5 on 2022-07-20 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_alter_category_stage_alter_stage_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalwork',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_works', to='project.work'),
        ),
        migrations.AlterField(
            model_name='message',
            name='box_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='project.boxchat'),
        ),
        migrations.AlterField(
            model_name='position',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='project.category'),
        ),
        migrations.AlterField(
            model_name='step',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='project.process'),
        ),
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='project.category'),
        ),
    ]
